apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Assume que o Prometheus estará a correr num container chamado 'prometheus' na mesma rede Docker
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
