-- Migration: Motor Agronômico NPK Base
-- Created at: 2026-04-03

-- 1. Create ref_cultura_extracao table
CREATE TABLE IF NOT EXISTS public.ref_cultura_extracao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura TEXT NOT NULL,
    produtividade_referencia_t_ha NUMERIC NOT NULL CHECK (produtividade_referencia_t_ha > 0),
    extracao_n_kg_t NUMERIC NOT NULL CHECK (extracao_n_kg_t >= 0),
    extracao_p2o5_kg_t NUMERIC NOT NULL CHECK (extracao_p2o5_kg_t >= 0),
    extracao_k2o_kg_t NUMERIC NOT NULL CHECK (extracao_k2o_kg_t >= 0),
    fonte_referencia TEXT,
    ano_referencia INTEGER,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uk_cultura_produtividade UNIQUE (cultura, produtividade_referencia_t_ha)
);

-- 2. Create ref_adubos_organicos table
CREATE TABLE IF NOT EXISTS public.ref_adubos_organicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    n_total_percentual NUMERIC NOT NULL CHECK (n_total_percentual >= 0 AND n_total_percentual <= 100),
    p2o5_total_percentual NUMERIC NOT NULL CHECK (p2o5_total_percentual >= 0 AND p2o5_total_percentual <= 100),
    k2o_total_percentual NUMERIC NOT NULL CHECK (k2o_total_percentual >= 0 AND k2o_total_percentual <= 100),
    taxa_liberacao_n_ciclo1 NUMERIC NOT NULL CHECK (taxa_liberacao_n_ciclo1 >= 0 AND taxa_liberacao_n_ciclo1 <= 1),
    taxa_liberacao_p_ciclo1 NUMERIC NOT NULL CHECK (taxa_liberacao_p_ciclo1 >= 0 AND taxa_liberacao_p_ciclo1 <= 1),
    taxa_liberacao_k_ciclo1 NUMERIC NOT NULL CHECK (taxa_liberacao_k_ciclo1 >= 0 AND taxa_liberacao_k_ciclo1 <= 1),
    base_seca BOOLEAN DEFAULT false,
    fonte_referencia TEXT,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Trigger/functions for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_ref_cultura_extracao ON public.ref_cultura_extracao;
CREATE TRIGGER set_updated_at_ref_cultura_extracao
BEFORE UPDATE ON public.ref_cultura_extracao
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_ref_adubos_organicos ON public.ref_adubos_organicos;
CREATE TRIGGER set_updated_at_ref_adubos_organicos
BEFORE UPDATE ON public.ref_adubos_organicos
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- 4. Enable RLS
ALTER TABLE public.ref_cultura_extracao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ref_adubos_organicos ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies
-- ref_cultura_extracao
CREATE POLICY "Autenticados podem ler ref_cultura_extracao"
ON public.ref_cultura_extracao FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Admins podem tudo em ref_cultura_extracao"
ON public.ref_cultura_extracao FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ref_adubos_organicos
CREATE POLICY "Autenticados podem ler ref_adubos_organicos"
ON public.ref_adubos_organicos FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Admins podem tudo em ref_adubos_organicos"
ON public.ref_adubos_organicos FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- 6. Insert Seed Data
INSERT INTO public.ref_cultura_extracao 
    (cultura, produtividade_referencia_t_ha, extracao_n_kg_t, extracao_p2o5_kg_t, extracao_k2o_kg_t, fonte_referencia)
VALUES 
    ('Alface', 20, 2.5, 1.2, 3.5, 'Estimativa Base'),
    ('Tomate', 80, 3.0, 1.1, 5.0, 'Estimativa Base')
ON CONFLICT (cultura, produtividade_referencia_t_ha) DO NOTHING;

INSERT INTO public.ref_adubos_organicos 
    (nome, n_total_percentual, p2o5_total_percentual, k2o_total_percentual, taxa_liberacao_n_ciclo1, taxa_liberacao_p_ciclo1, taxa_liberacao_k_ciclo1)
VALUES
    ('Esterco Bovino Curtido', 1.5, 1.0, 2.0, 0.3, 0.6, 1.0),
    ('Torta de Mamona', 5.0, 1.5, 1.0, 0.45, 0.65, 0.9)
ON CONFLICT (nome) DO NOTHING;

-- 7. Create Core Function RPC
CREATE OR REPLACE FUNCTION public.calcular_balanco_nutricional(
    p_cultura text,
    p_meta_t_ha numeric,
    p_adubo_nome text
)
RETURNS json AS $$
DECLARE
    v_extracao RECORD;
    v_adubo RECORD;
    v_demanda_n_kg numeric;
    v_n_disponivel_kg numeric;
    v_dose_recomendada_kg numeric;
    v_fornecimento_p_kg numeric;
    v_fornecimento_k_kg numeric;
BEGIN
    -- Busque a extração da cultura informada
    SELECT * INTO v_extracao 
    FROM public.ref_cultura_extracao 
    WHERE cultura ILIKE p_cultura 
    ORDER BY id ASC LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Cultura não encontrada: %', p_cultura;
    END IF;

    -- Busque os teores do adubo informado
    SELECT * INTO v_adubo
    FROM public.ref_adubos_organicos
    WHERE nome ILIKE p_adubo_nome
    ORDER BY id ASC LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Adubo não encontrado: %', p_adubo_nome;
    END IF;

    -- Calcule a Demanda de N em kg: p_meta_t_ha * extracao_n_kg_t
    v_demanda_n_kg := p_meta_t_ha * v_extracao.extracao_n_kg_t;

    -- Calcule o N disponível por 1 tonelada de adubo (transformando em kg disponiveis por 1 kg de adubo)
    -- N disponível por 1 ton = 1000 * (n_total_percentual / 100) * taxa_liberacao_n_ciclo1
    -- Em 1 kg de adubo = (n_total_percentual / 100) * taxa_liberacao_n_ciclo1
    v_n_disponivel_kg := (v_adubo.n_total_percentual / 100.0) * v_adubo.taxa_liberacao_n_ciclo1;

    -- Se o adubo não tem N para liberar
    IF v_n_disponivel_kg <= 0 THEN
        RAISE EXCEPTION 'Adubo tem 0 de N disponível: %', p_adubo_nome;
    END IF;

    -- Calcule a dose recomendada do adubo em kg para bater a meta de N e Arredonde para inteiro
    v_dose_recomendada_kg := ROUND(v_demanda_n_kg / v_n_disponivel_kg);

    -- Calcule o quanto essa dose de adubo vai fornecer de P e K reais no ciclo 1
    v_fornecimento_p_kg := v_dose_recomendada_kg * (v_adubo.p2o5_total_percentual / 100.0) * v_adubo.taxa_liberacao_p_ciclo1;
    v_fornecimento_k_kg := v_dose_recomendada_kg * (v_adubo.k2o_total_percentual / 100.0) * v_adubo.taxa_liberacao_k_ciclo1;

    -- Retorne um JSON
    RETURN json_build_object(
        'dose_recomendada_kg', v_dose_recomendada_kg,
        'demanda_n_kg', v_demanda_n_kg,
        'fornecimento_p_kg', v_fornecimento_p_kg,
        'fornecimento_k_kg', v_fornecimento_k_kg
    );
END;
$$ LANGUAGE plpgsql;
