-- Migration: Core Application Tables (previously dashboard-only)
-- Created at: 2026-04-02
-- These tables existed in Supabase Cloud only. They are the foundational
-- tables that all other migrations reference via foreign keys.

-- ── propriedades ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.propriedades (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
    nome                  TEXT NOT NULL,
    area_total_ha         NUMERIC,
    cidade                TEXT,
    uf                    TEXT,
    user_id               UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    tem_producao_paralela BOOLEAN DEFAULT false,
    modalidade_predominante public.modalidade_producao_enum DEFAULT 'ORGANICO',
    car                   TEXT,
    inscricao_estadual    TEXT,
    matricula             TEXT,
    endereco_cadastral    TEXT
);

ALTER TABLE public.propriedades ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários gerenciam suas propriedades"
ON public.propriedades FOR ALL TO authenticated
USING (user_id = auth.uid());

-- ── pmos ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMPTZ DEFAULT now() NOT NULL,
    form_data           JSONB,
    nome_identificador  TEXT,
    status              TEXT,
    version             BIGINT,
    user_id             UUID DEFAULT auth.uid() REFERENCES auth.users(id),
    propriedade_id      BIGINT REFERENCES public.propriedades(id),
    cultura             TEXT NOT NULL,
    produtividade_kg_ha NUMERIC NOT NULL
);

ALTER TABLE public.pmos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários gerenciam seus PMOs"
ON public.pmos FOR ALL TO authenticated
USING (user_id = auth.uid());

-- ── talhoes ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.talhoes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMPTZ DEFAULT now() NOT NULL,
    pmo_id              BIGINT REFERENCES public.pmos(id),
    user_id             UUID DEFAULT auth.uid() REFERENCES auth.users(id),
    nome                TEXT NOT NULL,
    geometry            JSONB,
    cor                 TEXT DEFAULT '#16a34a',
    area_ha             NUMERIC,
    active              BOOLEAN DEFAULT true,
    cultura             TEXT DEFAULT 'Não informada',
    area_total_m2       NUMERIC,
    cor_identificacao   TEXT DEFAULT '#4CAF50',
    tipo                TEXT DEFAULT 'produtivo',
    ph_solo             NUMERIC,
    v_percent           NUMERIC,
    teor_argila         NUMERIC,
    materia_organica    NUMERIC,
    fosforo             NUMERIC,
    potassio            NUMERIC,
    silte               NUMERIC,
    areia               NUMERIC,
    ph_agua             NUMERIC,
    status_certificacao TEXT DEFAULT 'Certificado',
    propriedade_id      BIGINT REFERENCES public.propriedades(id),
    fill_color          TEXT DEFAULT '#3bb444',
    border_color        TEXT DEFAULT '#228b22',
    modalidade_producao public.modalidade_producao_enum DEFAULT 'ORGANICO'
);

ALTER TABLE public.talhoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários gerenciam seus talhões"
ON public.talhoes FOR ALL TO authenticated
USING (user_id = auth.uid());

-- ── canteiros ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.canteiros (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at        TIMESTAMPTZ DEFAULT now(),
    talhao_id         BIGINT REFERENCES public.talhoes(id) ON DELETE CASCADE,
    nome              TEXT NOT NULL,
    comprimento_metros NUMERIC DEFAULT 10.0,
    largura_metros    NUMERIC DEFAULT 1.0,
    grid_x            INTEGER DEFAULT 0,
    grid_y            INTEGER DEFAULT 0,
    status            TEXT DEFAULT 'livre',
    area_total_m2     NUMERIC,
    tipo              TEXT DEFAULT 'Canteiro',
    tipo_estrutura    TEXT DEFAULT 'canteiro',
    profundidade_metros NUMERIC,
    volume_m3         NUMERIC,
    quantidade        NUMERIC DEFAULT 1
);

ALTER TABLE public.canteiros ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via talhão do usuário"
ON public.canteiros FOR ALL TO authenticated
USING (
    talhao_id IN (SELECT id FROM public.talhoes WHERE user_id = auth.uid())
);

-- ── ciclos_cultivo ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ciclos_cultivo (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at            TIMESTAMPTZ DEFAULT now(),
    canteiro_id           UUID REFERENCES public.canteiros(id) ON DELETE CASCADE,
    produto               TEXT NOT NULL,
    variedade             TEXT,
    data_plantio          DATE DEFAULT CURRENT_DATE,
    data_colheita_prevista DATE,
    data_encerramento     DATE,
    ativo                 BOOLEAN DEFAULT true,
    pmo_id                BIGINT REFERENCES public.pmos(id)
);

ALTER TABLE public.ciclos_cultivo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via canteiro do usuário"
ON public.ciclos_cultivo FOR ALL TO authenticated
USING (
    canteiro_id IN (
        SELECT c.id FROM public.canteiros c
        JOIN public.talhoes t ON c.talhao_id = t.id
        WHERE t.user_id = auth.uid()
    )
);

-- ── analises_solo ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.analises_solo (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    data_analise          DATE DEFAULT now(),
    laboratorio           TEXT,
    ph_agua               NUMERIC,
    fosforo               NUMERIC,
    potassio              NUMERIC,
    calcio                NUMERIC,
    magnesio              NUMERIC,
    saturacao_bases       NUMERIC,
    materia_organica      NUMERIC,
    iqs                   NUMERIC,
    argila                NUMERIC,
    areia                 NUMERIC,
    silte                 NUMERIC,
    classificacao_textural TEXT,
    created_at            TIMESTAMPTZ DEFAULT timezone('utc', now()),
    talhao_id             BIGINT REFERENCES public.talhoes(id)
);

ALTER TABLE public.analises_solo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via talhão do usuário"
ON public.analises_solo FOR ALL TO authenticated
USING (
    talhao_id IN (SELECT id FROM public.talhoes WHERE user_id = auth.uid())
);

-- ── caderno_campo ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.caderno_campo (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id              BIGINT REFERENCES public.pmos(id),
    data_registro       DATE DEFAULT now(),
    tipo_atividade      TEXT NOT NULL,
    secao_origem        TEXT,
    produto             TEXT,
    talhao_canteiro     TEXT,
    quantidade_valor    NUMERIC,
    quantidade_unidade  TEXT,
    detalhes_tecnicos   JSONB DEFAULT '{}',
    observacao_original TEXT,
    criado_em           TIMESTAMPTZ DEFAULT now(),
    user_id             UUID DEFAULT auth.uid() REFERENCES auth.users(id),
    talhao_id           BIGINT REFERENCES public.talhoes(id),
    atividades          JSONB,
    sistema             TEXT,
    status              TEXT,
    audio_url           TEXT,
    propriedade_id      BIGINT REFERENCES public.propriedades(id),
    houve_descartes     BOOLEAN DEFAULT false,
    qtd_descartes       NUMERIC,
    unidade_descartes   TEXT,
    canteiro_ids        UUID[],
    tipo_operacao       TEXT,
    responsavel         TEXT,
    equipamentos        TEXT[],
    lote                TEXT,
    destino             TEXT,
    classificacao       TEXT,
    valor_total         NUMERIC,
    origem              TEXT,
    nota_fiscal         TEXT,
    fornecedor          TEXT,
    modalidade_aplicada public.modalidade_producao_enum DEFAULT 'ORGANICO',
    data                DATE,
    raw_payload_id      UUID
);

ALTER TABLE public.caderno_campo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários veem seus registros de caderno"
ON public.caderno_campo FOR ALL TO authenticated
USING (user_id = auth.uid());

-- ── caderno_campo_canteiros (junction) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.caderno_campo_canteiros (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    caderno_campo_id UUID REFERENCES public.caderno_campo(id) ON DELETE CASCADE,
    propriedade_id BIGINT REFERENCES public.propriedades(id),
    codigo_lote    TEXT NOT NULL,
    cultura        TEXT NOT NULL,
    quantidade     NUMERIC NOT NULL,
    data_colheita  DATE NOT NULL,
    qr_code_url    TEXT,
    created_at     TIMESTAMPTZ DEFAULT now(),
    user_id        UUID DEFAULT auth.uid() REFERENCES auth.users(id)
);

ALTER TABLE public.caderno_campo_canteiros ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários veem seus lotes de caderno"
ON public.caderno_campo_canteiros FOR ALL TO authenticated
USING (user_id = auth.uid());

-- ── culturas_anuais ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.culturas_anuais (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmo_id    BIGINT REFERENCES public.pmos(id),
    cultura   TEXT,
    area_ha   NUMERIC,
    ano_safra TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.culturas_anuais ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.culturas_anuais FOR ALL TO authenticated
USING (
    pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid())
);

-- ── insumos_proibidos ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.insumos_proibidos (
    id         SERIAL PRIMARY KEY,
    nome       TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.insumos_proibidos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Todos autenticados leem insumos proibidos"
ON public.insumos_proibidos FOR SELECT TO authenticated USING (true);

-- ── referencia_agronomica ─────────────────────────────────────────────────────
-- Simple lookup table: crop name → productivity reference
-- NOTE: 20260421_capacidade_fisica_trigger.sql expects (cultura TEXT PK, produtividade_kg_ha NUMERIC)
CREATE TABLE IF NOT EXISTS public.referencia_agronomica (
    cultura             TEXT PRIMARY KEY,
    produtividade_kg_ha NUMERIC NOT NULL
);

ALTER TABLE public.referencia_agronomica ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Todos autenticados leem referencia agronomica"
ON public.referencia_agronomica FOR SELECT TO authenticated USING (true);

-- ── lotes_rastreabilidade ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lotes_rastreabilidade (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    caderno_campo_id UUID REFERENCES public.caderno_campo(id),
    propriedade_id BIGINT REFERENCES public.propriedades(id),
    codigo_lote    TEXT NOT NULL,
    cultura        TEXT NOT NULL,
    quantidade     NUMERIC NOT NULL,
    data_colheita  DATE NOT NULL,
    qr_code_url    TEXT,
    created_at     TIMESTAMPTZ DEFAULT now(),
    user_id        UUID DEFAULT auth.uid() REFERENCES auth.users(id)
);

ALTER TABLE public.lotes_rastreabilidade ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários veem seus lotes"
ON public.lotes_rastreabilidade FOR ALL TO authenticated
USING (user_id = auth.uid());

-- ── pmo_culturas ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_culturas (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id     BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    produto    TEXT,
    variedade  TEXT,
    ciclo      TEXT,
    data_plantio DATE,
    area_plantada TEXT,
    estimativa_colheita TEXT,
    localizacao JSONB,
    status     TEXT DEFAULT 'Planejado',
    producao_unidade TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL
);

ALTER TABLE public.pmo_culturas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_culturas FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_manejo ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_manejo (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id              BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
    produto_manejo      TEXT,
    cultura_destino     TEXT,
    epoca_frequencia    TEXT,
    procedencia         TEXT,
    composicao          TEXT,
    marca               TEXT,
    dosagem             TEXT,
    propriedade_id      BIGINT REFERENCES public.propriedades(id)
);

ALTER TABLE public.pmo_manejo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_manejo FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_pragas ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_pragas (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id           BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    praga_alvo       TEXT,
    produto_controle TEXT,
    ingrediente_ativo TEXT
);

ALTER TABLE public.pmo_pragas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_pragas FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_equipamentos ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_equipamentos (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id     BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
    tipo       TEXT,
    especies   TEXT,
    origem     TEXT,
    quantidade TEXT,
    sistema_organico BOOLEAN DEFAULT true,
    data_compra DATE,
    propriedade_id BIGINT REFERENCES public.propriedades(id)
);

ALTER TABLE public.pmo_equipamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_equipamentos FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_insumos ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_insumos (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id              BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
    insumo              TEXT,
    fonte               TEXT,
    quantidade          TEXT,
    data_aplicacao      DATE,
    metodo_aplicacao    TEXT,
    talhoes_aplicados   JSONB,
    modalidade_aplicada public.modalidade_producao_enum DEFAULT 'ORGANICO'
);

ALTER TABLE public.pmo_insumos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_insumos FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_propagacao ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_propagacao (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id     BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
    tipo       TEXT,
    especies   TEXT,
    origem     TEXT,
    quantidade TEXT,
    sistema_organico BOOLEAN DEFAULT true,
    data_compra DATE,
    propriedade_id BIGINT REFERENCES public.propriedades(id)
);

ALTER TABLE public.pmo_propagacao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_propagacao FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_limpeza ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_limpeza (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmo_id            BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    data_limpeza      DATE DEFAULT CURRENT_DATE NOT NULL,
    item_area         TEXT NOT NULL,
    tipo_limpeza      TEXT NOT NULL,
    produto_utilizado TEXT,
    dosagem           TEXT,
    responsavel       TEXT NOT NULL,
    observacao        TEXT,
    created_at        TIMESTAMPTZ DEFAULT now(),
    propriedade_id    BIGINT REFERENCES public.propriedades(id)
);

ALTER TABLE public.pmo_limpeza ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_limpeza FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));

-- ── pmo_clima ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pmo_clima (
    id              UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid() NOT NULL,
    pmo_id          BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ DEFAULT now() NOT NULL,
    temperatura_c   NUMERIC,
    umidade         INTEGER,
    vento_kph       NUMERIC,
    condicao_texto  TEXT,
    condicao_icone  TEXT,
    previsao_dias   JSONB,
    propriedade_id  BIGINT REFERENCES public.propriedades(id)
);

ALTER TABLE public.pmo_clima ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso via PMO do usuário"
ON public.pmo_clima FOR ALL TO authenticated
USING (pmo_id IN (SELECT id FROM public.pmos WHERE user_id = auth.uid()));
