-- DT-133: fecha a decisão de produto que travava o item.
--
-- Contexto (ver debitos_tecnicos.md): a policy de pmo_limpeza/pmo_propagacao
-- dava acesso de ESCRITA a quem possui a propriedade_id, mesmo sem possuir o
-- pmo_id — um dono de propriedade podia reatribuir pmo_id pra um PMO de outro
-- tenant e a checagem continuava satisfeita. A pergunta pendente era se esse
-- branch por propriedade_id era intencional (colaboração multi-tenant) ou
-- resíduo.
--
-- Decisão registrada em 2026-09-09: NÃO é colaboração de escrita por
-- propriedade. O caso real de colaboração é outro — agrônomo, técnico de
-- cooperativa, OCS, OPAC ou certificadora precisam LER o PMO de um produtor
-- que não são, nunca escrever. Este arquivo:
--   1. Remove o branch propriedade_id do WITH CHECK/USING de
--      pmo_limpeza/pmo_propagacao — escrita volta a exigir posse direta do
--      pmo_id (fecha o DT-133 de verdade, não só formaliza o bug).
--   2. Cria pmo_acessos_profissionais, a tabela de concessão explícita que
--      modela o caso real.
--   3. Adiciona policies de SELECT (só leitura, nenhuma de escrita) em pmos/
--      pmo_limpeza/pmo_propagacao para quem tem uma concessão ativa.
--
-- Versão mínima, sem RPC nem UI de concessão — conceder/revogar hoje é via
-- INSERT/UPDATE direto na tabela (pelo dono do PMO, a RLS não permite mais
-- ninguém). UI de concessão pro produtor e extensão pras demais tabelas
-- pmo_* ficam para quando o produto decidir a superfície (frontend antes do
-- WhatsApp/chat, ver discussão no PLAN-fase0-fechamento-2026-09-09.md).
--
-- Fora de escopo deste arquivo: DT-135/DT-136/DT-137 (schema drift entre
-- produção e staging em pmo_equipamentos/pmo_insumos/caderno_campo_canteiros)
-- — precisam de reconciliação de schema antes de qualquer RLS nova.

-- ── 1. pmo_limpeza / pmo_propagacao: escrita volta a exigir posse do pmo_id ──
--
-- Nomes de policy DIVERGEM entre staging e produção pro mesmo propósito
-- (confirmado via introspecção em 2026-09-09, mesma lição repetida desde o
-- DT-22/DT-70): produção tem "Users can manage their own pmo_limpeza" (com
-- o branch propriedade_id, é o bug do DT-133); staging tem "Acesso via PMO
-- do usuário" (já sem o branch — staging nunca teve o bug). E produção
-- estava com `with_check` NULL apesar do DT-132 (20260909050000) já ter
-- sido commitado no repo com WITH CHECK pra essas duas tabelas — ou seja,
-- aquela migration nunca chegou a rodar de fato em produção. Este arquivo
-- dropa os dois nomes possíveis pra ficar idempotente nos dois ambientes.

DROP POLICY IF EXISTS "Users can manage their own pmo_limpeza" ON public.pmo_limpeza;
DROP POLICY IF EXISTS "Acesso via PMO do usuário" ON public.pmo_limpeza;
CREATE POLICY "Users can manage their own pmo_limpeza" ON public.pmo_limpeza
  FOR ALL TO authenticated
  USING (
    auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_limpeza.pmo_id)
  )
  WITH CHECK (
    auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_limpeza.pmo_id)
  );

DROP POLICY IF EXISTS "Users can manage their own pmo_propagacao" ON public.pmo_propagacao;
DROP POLICY IF EXISTS "Acesso via PMO do usuário" ON public.pmo_propagacao;
CREATE POLICY "Users can manage their own pmo_propagacao" ON public.pmo_propagacao
  FOR ALL TO authenticated
  USING (
    auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_propagacao.pmo_id)
  )
  WITH CHECK (
    auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_propagacao.pmo_id)
  );

-- ── 2. Tabela de concessão explícita ─────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pmo_acessos_profissionais (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmo_id           BIGINT NOT NULL REFERENCES public.pmos(id) ON DELETE CASCADE,
    profissional_id  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    papel            TEXT NOT NULL CHECK (papel IN ('agronomo', 'tecnico_cooperativa', 'ocs', 'opac', 'certificadora')),
    concedido_por     UUID NOT NULL REFERENCES auth.users(id),
    concedido_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
    revogado_em       TIMESTAMPTZ
);

COMMENT ON TABLE public.pmo_acessos_profissionais IS
  'Concessão explícita de leitura de um PMO a um profissional (agrônomo, técnico de cooperativa, OCS, OPAC, certificadora). Nunca dá acesso de escrita. revogado_em NULL = concessão ativa; histórico nunca é deletado (mesmo princípio do Caderno de Campo: registro de compliance).';

-- Só uma concessão ativa por (pmo, profissional) por vez — revogar e
-- conceder de novo cria uma linha nova, preservando o histórico.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pmo_acessos_profissionais_ativa
  ON public.pmo_acessos_profissionais (pmo_id, profissional_id)
  WHERE revogado_em IS NULL;

CREATE INDEX IF NOT EXISTS idx_pmo_acessos_profissionais_profissional
  ON public.pmo_acessos_profissionais (profissional_id)
  WHERE revogado_em IS NULL;

ALTER TABLE public.pmo_acessos_profissionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pmo_acessos_profissionais FORCE ROW LEVEL SECURITY;

-- Dono do PMO e o profissional concedido enxergam a linha; ninguém mais.
CREATE POLICY "Dono do PMO e profissional veem a concessão"
  ON public.pmo_acessos_profissionais FOR SELECT TO authenticated
  USING (
    auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_acessos_profissionais.pmo_id)
    OR profissional_id = auth.uid()
  );

-- Só o dono do PMO concede, e só em nome de si mesmo (concedido_por não é
-- livre) — impede um profissional se autoconceder ou forjar quem concedeu.
CREATE POLICY "Só o dono do PMO concede acesso"
  ON public.pmo_acessos_profissionais FOR INSERT TO authenticated
  WITH CHECK (
    concedido_por = auth.uid()
    AND auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_acessos_profissionais.pmo_id)
  );

-- Só o dono do PMO revoga (UPDATE); o trigger abaixo garante que a única
-- coisa que um UPDATE pode mudar é revogado_em.
CREATE POLICY "Só o dono do PMO revoga acesso"
  ON public.pmo_acessos_profissionais FOR UPDATE TO authenticated
  USING (auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_acessos_profissionais.pmo_id))
  WITH CHECK (auth.uid() IN (SELECT pmos.user_id FROM public.pmos WHERE pmos.id = pmo_acessos_profissionais.pmo_id));

-- Nenhuma policy de DELETE: concessão só se revoga (revogado_em), nunca se
-- apaga — mesmo princípio de nunca deletar Caderno de Campo, aqui aplicado
-- ao histórico de quem teve acesso a quê (auditoria de certificadora/OPAC).

CREATE OR REPLACE FUNCTION public.pmo_acessos_profissionais_bloqueia_alteracao_campos_imutaveis()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.pmo_id IS DISTINCT FROM OLD.pmo_id
     OR NEW.profissional_id IS DISTINCT FROM OLD.profissional_id
     OR NEW.papel IS DISTINCT FROM OLD.papel
     OR NEW.concedido_por IS DISTINCT FROM OLD.concedido_por
     OR NEW.concedido_em IS DISTINCT FROM OLD.concedido_em THEN
    RAISE EXCEPTION 'pmo_acessos_profissionais: apenas revogado_em pode ser alterado após a concessão criada';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pmo_acessos_profissionais_imutavel ON public.pmo_acessos_profissionais;
CREATE TRIGGER trg_pmo_acessos_profissionais_imutavel
  BEFORE UPDATE ON public.pmo_acessos_profissionais
  FOR EACH ROW EXECUTE FUNCTION public.pmo_acessos_profissionais_bloqueia_alteracao_campos_imutaveis();

-- ── 3. Leitura (só SELECT) para profissionais com concessão ativa ───────

CREATE POLICY "Profissionais autorizados leem o PMO"
  ON public.pmos FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.pmo_acessos_profissionais a
      WHERE a.pmo_id = pmos.id AND a.profissional_id = auth.uid() AND a.revogado_em IS NULL
    )
  );

CREATE POLICY "Profissionais autorizados leem pmo_limpeza"
  ON public.pmo_limpeza FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.pmo_acessos_profissionais a
      WHERE a.pmo_id = pmo_limpeza.pmo_id AND a.profissional_id = auth.uid() AND a.revogado_em IS NULL
    )
  );

CREATE POLICY "Profissionais autorizados leem pmo_propagacao"
  ON public.pmo_propagacao FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.pmo_acessos_profissionais a
      WHERE a.pmo_id = pmo_propagacao.pmo_id AND a.profissional_id = auth.uid() AND a.revogado_em IS NULL
    )
  );
