-- Migration: Multi-Tenancy (Cooperativas e Associações)
-- Created at: 2026-04-01

-- 1. Create organizacoes table
CREATE TABLE IF NOT EXISTS public.organizacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cnpj TEXT UNIQUE,
    tipo TEXT CHECK (tipo IN ('cooperativa', 'associacao', 'spg', 'grupo_informal')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create organizacao_membros (N:N with Propriedade)
CREATE TABLE IF NOT EXISTS public.organizacao_membros (
    organizacao_id BIGINT REFERENCES public.organizacoes(id) ON DELETE CASCADE,
    propriedade_id BIGINT REFERENCES public.propriedades(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'membro',
    data_filiacao DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (organizacao_id, propriedade_id)
);

-- 3. Data Migration for demandas_coletivas
-- Create a default organization to bridge existing data
DO $$
DECLARE
    default_org_id BIGINT;
BEGIN
    -- Check if we already have a default org
    SELECT id INTO default_org_id FROM public.organizacoes WHERE nome = 'Cooperativa Central (Padrão)' LIMIT 1;
    
    IF default_org_id IS NULL THEN
        INSERT INTO public.organizacoes (nome, tipo) 
        VALUES ('Cooperativa Central (Padrão)', 'cooperativa')
        RETURNING id INTO default_org_id;
    END IF;

    -- Update existing demands to point to this default org if they are null
    UPDATE public.demandas_coletivas 
    SET cooperativa_id = default_org_id 
    WHERE cooperativa_id IS NULL;
END $$;

-- 4. Enforce Integrity on demandas_coletivas
ALTER TABLE public.demandas_coletivas 
    ALTER COLUMN cooperativa_id SET NOT NULL,
    ADD CONSTRAINT fk_demandas_organizacao 
    FOREIGN KEY (cooperativa_id) REFERENCES public.organizacoes(id);

-- 5. Enable RLS
ALTER TABLE public.organizacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizacao_membros ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies

-- organizacoes: Membros podem ver sua organização
CREATE POLICY "Membros podem ver sua organizacao" 
ON public.organizacoes FOR SELECT 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.organizacao_membros 
        WHERE organizacao_id = public.organizacoes.id 
        AND propriedade_id IN (SELECT id FROM public.propriedades WHERE user_id = auth.uid())
    ) OR 
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- organizacao_membros: Membros podem ver outros membros da mesma org
CREATE POLICY "Membros podem ver membros da mesma organizacao" 
ON public.organizacao_membros FOR SELECT 
TO authenticated 
USING (
    organizacao_id IN (
        SELECT organizacao_id FROM public.organizacao_membros 
        WHERE propriedade_id IN (SELECT id FROM public.propriedades WHERE user_id = auth.uid())
    ) OR 
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Admin policies
CREATE POLICY "Admins podem tudo nas organizacoes" 
ON public.organizacoes FOR ALL 
TO authenticated 
USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Admins podem tudo nos membros" 
ON public.organizacao_membros FOR ALL 
TO authenticated 
USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
