-- DT-131: reconciliação de schema — não era "colunas órfãs em produção", era
-- staging defasado. Descoberto ao verificar antes de encarar o DT-137.
--
-- O débito original dizia que a migration corretiva (20260817214500) tinha
-- adicionado canteiro_id + FK mas nenhuma migration removera as 5 colunas
-- órfãs de rastreabilidade (codigo_lote/cultura/quantidade/data_colheita/
-- qr_code_url) "que continuam na tabela em produção sem uso". Verificado
-- ao vivo em 2026-09-09: **produção já está limpa** — só tem
-- id/created_at/caderno_campo_id/canteiro_id, exatamente o modelo de junção
-- esperado, com FK e policy corretas (join via caderno_campo.user_id).
-- É **staging** que ainda carrega o schema antigo (as 5 colunas órfãs +
-- user_id direto + propriedade_id, tudo coexistindo com canteiro_id) e a
-- policy antiga por user_id direto (o mesmo achado do DT-137, que travava
-- nisso: "não dá pra saber se produção migrou de fato pro modelo por FK
-- sem revisar o DT-131 primeiro" — agora sabemos: produção migrou, sim).
--
-- Zero linhas em staging (confirmado antes de dropar) — sem perda de dado.
-- Produção tem 16 linhas, schema já correto — não precisa de nenhuma
-- mudança de dado ou coluna, só recebe explicitamente o WITH CHECK que a
-- policy "Users manage own canteiros" não tinha (FOR ALL sem WITH CHECK
-- reusa a USING automaticamente no Postgres — não era um bug de segurança,
-- só deixa explícito, mesmo padrão adotado no resto desta sessão).
--
-- Achado à parte, não corrigido aqui (fora do escopo do DT-131): produção
-- tem DUAS foreign keys em canteiro_id
-- (`caderno_campo_canteiros_canteiro_id_fkey` ON DELETE CASCADE e
-- `fk_canteiro` ON DELETE RESTRICT) — a RESTRICT bloqueia qualquer DELETE
-- de canteiro referenciado antes da CASCADE ter chance de agir, tornando a
-- CASCADE inerte. Não é bug de segurança, é higiene de constraint; registrar
-- como item separado se vier a importar.

DROP TABLE IF EXISTS public.caderno_campo_canteiros CASCADE;
CREATE TABLE public.caderno_campo_canteiros (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    caderno_campo_id UUID NOT NULL REFERENCES public.caderno_campo(id) ON DELETE CASCADE,
    canteiro_id      UUID NOT NULL REFERENCES public.canteiros(id) ON DELETE CASCADE
);
ALTER TABLE public.caderno_campo_canteiros ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own canteiros" ON public.caderno_campo_canteiros
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.caderno_campo cc
      WHERE cc.id = caderno_campo_canteiros.caderno_campo_id AND cc.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.caderno_campo cc
      WHERE cc.id = caderno_campo_canteiros.caderno_campo_id AND cc.user_id = auth.uid()
    )
  );
